name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint

  deploy:
    needs: [lint]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/hotfix/o2switch-deploy'
    runs-on: ubuntu-latest
    environment: Deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Whitelist IP address
        uses: d9beuD/o2switch-whitelisting@v1.0.1
        with:
          o2switch_username: ${{ secrets.O2SWITCH_USER }}
          o2switch_password: ${{ secrets.O2SWITCH_PASSWORD }}
          o2switch_host: ${{ secrets.O2SWITCH_HOST }}
      
      - name: SSH Deployment
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/sites/disgame-client
            git pull origin main
            npm install
            npm run build
